services:
  elastic:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.0.1'
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - '127.0.0.1:9200:9200'
      - '127.0.0.1:9300:9300'

  grafana:
    image: 'grafana/grafana-oss'
    ports:
      - '127.0.0.1:3000:3000'